import {test} from 'node:test';import assert from 'node:assert/strict';import {base64} from '../src/ledger.mjs';import {acceptedPolicyService} from '../src/policy/service.mjs';
const id='a'.repeat(64),sha=c=>c.repeat(40);
function storage(){let data=new Map(),tail=Promise.resolve();const api={get:async k=>structuredClone(data.get(k)),put:async(k,v)=>data.set(k,structuredClone(v)),delete:async k=>data.delete(k),transaction(fn){const work=tail.then(async()=>{const before=structuredClone(data);try{return await fn(api);}catch(e){data=before;throw e;}});tail=work.catch(()=>{});return work;}};return api;}
async function signer(){const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);const bytes=await crypto.subtle.exportKey('raw',pair.publicKey);const keyID=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');return {pair,keyID,publicKeyX963:base64(bytes)};}
async function fixture(){
 const now=Math.floor(Date.now()/1000),owner=await signer(),validator=await signer();
 const trust={appID:1,installationID:2,repositoryIDs:[7],acceptedPolicyRevision:1,acceptedPolicyDigest:'b'.repeat(64),targetRef:'refs/heads/main',audiencePrefix:'repoctl',repository:'owner/delivery_control',repositoryID:10,ownerID:20,ref:'refs/heads/main',workflowRef:'owner/delivery_control/.github/workflows/promote.yml@refs/heads/main',workflowSHA:sha('a'),jobWorkflowRef:'owner/delivery_control/.github/workflows/executor.yml@refs/heads/main',jobWorkflowSHA:sha('a'),eventNames:['workflow_dispatch'],actorIDs:[30]};
 const policy={repositoryID:7,repository:'owner/project',targetRef:'refs/heads/main',revision:1,digest:trust.acceptedPolicyDigest,maxIntentTTL:300,ownerKeys:[{keyID:owner.keyID,publicKeyX963:owner.publicKeyX963}],validatorKeys:[{keyID:validator.keyID,publicKeyX963:validator.publicKeyX963}],executorTrust:trust};

 return {now,owner,validator,policy,trust};
}

async function setup(){const f=await fixture(),store=storage();let revoked=false;
const bootstrap={repositoryID:7,repository:'owner/project',ownerKeys:f.policy.ownerKeys,validatorKeys:f.policy.validatorKeys};
const service=acceptedPolicyService({storage:store,bootstrap,clock:()=>f.now,hardware:{verify:async()=>({keyID:f.owner.keyID,hardwareVerified:!revoked,revoked,proofDigest:'f'.repeat(64),validUntil:f.now+1000})}});
async function bundle(policy=f.policy,previousDigest='0'.repeat(64)){const body={policy,previousDigest,expiresAt:f.now+200},payload=JSON.stringify(body,null,2)+'\n';async function sign(role,s){const protocol=`repoctl-policy-${role}-v1`;return {protocol,keyID:s.keyID,encoding:'p1363',payload:Buffer.from(payload).toString('base64'),signature:base64(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},s.pair.privateKey,Buffer.from(protocol+'\n'+payload)))};}return {owner:await sign('owner',f.owner),validator:await sign('validator',f.validator)};}
return {...f,service,store,bundle,revoke:()=>{revoked=true;}};}
test('policy admission verifies two signatures and retains sequential revisions',async()=>{const f=await setup(),b=await f.bundle(),r=await f.service.admit(b);assert.deepEqual(await f.service.admit(b),r);assert.deepEqual(await f.service.current({repositoryID:7}),f.policy);const p={...f.policy,revision:2,executorTrust:{...f.trust,acceptedPolicyRevision:2}};await f.service.admit(await f.bundle(p,r.admissionDigest));assert.equal((await f.service.current({repositoryID:7})).revision,2);await assert.rejects(f.service.admit(await f.bundle(p)));});
test('policy admission refuses altered signatures, foreign target and revoked hardware',async()=>{const f=await setup(),b=await f.bundle();await assert.rejects(f.service.admit({...b,validator:{...b.validator,signature:base64(new Uint8Array(64))}}));await assert.rejects(f.service.admit(await f.bundle({...f.policy,repository:'other/project'})));f.revoke();await assert.rejects(f.service.admit(b));await assert.rejects(f.service.current({repositoryID:7}));});
test('policy readback rejects changed retained body and missing history',async()=>{const f=await setup();await f.service.admit(await f.bundle());const current=await f.store.get('accepted-policy:7');await f.store.put('accepted-policy:7',{...current,policy:{...current.policy,maxIntentTTL:1}});await assert.rejects(f.service.current({repositoryID:7}));await f.store.put('accepted-policy:7',current);await f.store.delete('accepted-policy-revision:7:1');await assert.rejects(f.service.current({repositoryID:7}));});
