import {test} from 'node:test';
import assert from 'node:assert/strict';
import {sign as nodeSign,createPrivateKey} from 'node:crypto';
import {canonical,digest,base64} from '../src/ledger.mjs';
import {signApproval} from '../src/promotion.mjs';
import {authorize,importPolicy} from '../src/authority/authorize.mjs';
import {authorityRequest} from '../src/authority/service.mjs';
import {AuthorizationCoordinator} from '../src/authority/coordinator.mjs';
const id='a'.repeat(64),sha=c=>c.repeat(40);
function storage(){let data=new Map(),tail=Promise.resolve();const api={get:async k=>structuredClone(data.get(k)),put:async(k,v)=>data.set(k,structuredClone(v)),delete:async k=>data.delete(k),transaction(fn){const work=tail.then(async()=>{const before=structuredClone(data);try{return await fn(api);}catch(e){data=before;throw e;}});tail=work.catch(()=>{});return work;}};return api;}
async function signer(){const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);const bytes=await crypto.subtle.exportKey('raw',pair.publicKey);const keyID=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');return {pair,keyID,publicKeyX963:base64(bytes)};}
async function fixture(){
 const now=Math.floor(Date.now()/1000),owner=await signer(),validator=await signer();
 const trust={appID:1,installationID:2,repositoryIDs:[7],acceptedPolicyRevision:1,acceptedPolicyDigest:'b'.repeat(64),targetRef:'refs/heads/main',audiencePrefix:'repoctl',repository:'owner/delivery_control',repositoryID:10,ownerID:20,ref:'refs/heads/main',workflowRef:'owner/delivery_control/.github/workflows/promote.yml@refs/heads/main',workflowSHA:sha('a'),jobWorkflowRef:'owner/delivery_control/.github/workflows/executor.yml@refs/heads/main',jobWorkflowSHA:sha('a'),eventNames:['workflow_dispatch'],actorIDs:[30]};
 const policy={repositoryID:7,repository:'owner/project',targetRef:'refs/heads/main',revision:1,digest:trust.acceptedPolicyDigest,maxIntentTTL:300,ownerKeys:[{keyID:owner.keyID,publicKeyX963:owner.publicKeyX963}],validatorKeys:[{keyID:validator.keyID,publicKeyX963:validator.publicKeyX963}],executorTrust:trust};
 const intent={repositoryID:7,sequence:1,previousDigest:'c'.repeat(64),baseSHA:sha('b'),commitSHA:sha('c'),sourceSHA:sha('d'),treeSHA:sha('e'),policyDigest:policy.digest,evidenceDigest:'d'.repeat(64),archiveDigests:['e'.repeat(64)],nonce:id,expiresAt:(now+250)*1000};
 async function runApproval(body,der=false){const payload=base64(new TextEncoder().encode(canonical(body))),message=Buffer.from('repoctl-execution-owner-v1\n'+canonical(body));const signature=der?nodeSign('sha256',message,createPrivateKey({key:Buffer.from(await crypto.subtle.exportKey('pkcs8',owner.pair.privateKey)),format:'der',type:'pkcs8'})):await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},owner.pair.privateKey,message);return {protocol:'repoctl-execution-owner-v1',keyID:owner.keyID,encoding:der?'der':'p1363',payload,signature:base64(signature)};}
 async function bundleFor(p=intent,changes={},der=false){const approvals={owner:await signApproval(p,'owner',owner.keyID,owner.pair.privateKey),validator:await signApproval(p,'validator',validator.keyID,validator.pair.privateKey)};const run={operationID:p.nonce,approvalDigest:await digest(approvals),repositoryID:7,repository:policy.repository,targetRef:policy.targetRef,policyRevision:policy.revision,policyDigest:policy.digest,executorTrustDigest:await digest(trust),runID:60,runAttempt:1,expiresAt:now+200,...changes};return {...approvals,executionOwner:await runApproval(run,der)};}
 const services={storage:storage(),policy:{current:async()=>policy},hardware:{verify:async()=>({keyID:owner.keyID,proofDigest:'f'.repeat(64),hardwareVerified:true,revoked:false,validUntil:now+1000})},evidence:{verify:async request=>({operationID:request.operationID,verified:true,intentDigest:await digest(request.intent)})},reconciliation:{observe:async({operationID,record})=>({operationID,state:'promoted',commitSHA:record.intent.commitSHA,receiptDigest:'9'.repeat(64),verified:true})}};
 return {now,owner,validator,policy,trust,intent,bundle:await bundleFor(),bundleFor,runApproval,services};
}
test('authority verifies independent promotion and exact-run approvals then retains idempotently',async()=>{const f=await fixture();const result=await authorize(f.bundle,f.services,f.now);assert.equal(result.operationID,id);assert.equal(result.runID,60);assert.deepEqual(await authorize(f.bundle,f.services,f.now),result);const record=await f.services.storage.get(`authority:${id}`);assert.equal(record.enrollmentProofDigest,'f'.repeat(64));assert.equal(record.record.operation.hardwareEnrollmentVerified,true);});
test('Apple-style DER execution approval works without changing reviewed bytes',async()=>{const f=await fixture();await authorize(await f.bundleFor(f.intent,{},true),f.services,f.now);});
test('execution signature changes and foreign trust, target, approval or expiry cannot admit',async()=>{const f=await fixture();for(const changes of [{executorTrustDigest:'0'.repeat(64)},{repository:'other/repo'},{targetRef:'refs/heads/master'},{approvalDigest:'0'.repeat(64)},{operationID:'0'.repeat(64)},{expiresAt:f.now+300},{runID:0}])await assert.rejects(authorize(await f.bundleFor(f.intent,changes),f.services,f.now));const altered=structuredClone(f.bundle);altered.executionOwner.signature=base64(new Uint8Array(64));await assert.rejects(authorize(altered,f.services,f.now));assert.equal(await f.services.storage.get(`authority:${id}`),undefined);});
test('software or revoked hardware and unverified archives cannot become trusted authorization',async()=>{for(const change of [{hardwareVerified:false},{revoked:true},{validUntil:0},{keyID:'0'.repeat(64)},{proofDigest:'bad'}]){const f=await fixture(),old=f.services.hardware.verify;f.services.hardware.verify=async()=>({...await old(),...change});await assert.rejects(authorize(f.bundle,f.services,f.now));assert.equal(await f.services.storage.get(`authority:${id}`),undefined);}const f=await fixture();f.services.evidence.verify=async()=>({operationID:id,verified:true,intentDigest:'0'.repeat(64)});await assert.rejects(authorize(f.bundle,f.services,f.now));});
test('same public key cannot be enrolled as independent validator; inventory aliases reject',async()=>{const f=await fixture();const p=structuredClone(f.policy);p.validatorKeys=p.ownerKeys;await assert.rejects(importPolicy(p));p.validatorKeys=[{keyID:'0'.repeat(64),publicKeyX963:f.owner.publicKeyX963}];await assert.rejects(importPolicy(p));});
test('concurrent generations permit only one pending operation for a repository',async()=>{const f=await fixture(),next={...f.intent,nonce:'2'.repeat(64)};const results=await Promise.allSettled([authorize(f.bundle,f.services,f.now),authorize(await f.bundleFor(next),f.services,f.now)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);});
test('load/check bind retained record and reject current policy or hardware revocation',async()=>{const f=await fixture();await authorize(f.bundle,f.services,f.now);const req=(path,body)=>new Request('https://internal'+path,{method:'POST',body:JSON.stringify(body)});const loaded=await authorityRequest(req('/v1/authorization/load',{operationID:id}),f.services,f.now);assert.equal(loaded.status,200);assert.equal(loaded.headers.get('cache-control'),'no-store');const record=await loaded.json();const check=()=>authorityRequest(req('/v1/authorization/check',{operationID:id,...record}),f.services,f.now);assert.equal((await check()).status,200);const altered={...record,intent:{...record.intent,commitSHA:sha('f')}};assert.equal((await authorityRequest(req('/v1/authorization/check',{operationID:id,...altered}),f.services,f.now)).status,403);f.services.hardware.verify=async()=>({revoked:true});assert.equal((await check()).status,403);});
test('reconciliation needs independent receipt and preserves nonce tombstone after completion',async()=>{const f=await fixture();await authorize(f.bundle,f.services,f.now);const request=()=>new Request('https://internal/v1/authorization/reconcile',{method:'POST',body:JSON.stringify({operationID:id})});const observe=f.services.reconciliation.observe;f.services.reconciliation.observe=async()=>({verified:true,state:'promoted',operationID:id,commitSHA:sha('f'),receiptDigest:'9'.repeat(64)});assert.equal((await authorityRequest(request(),f.services,f.now)).status,403);assert.equal(await f.services.storage.get('pending-repository:7'),id);f.services.reconciliation.observe=observe;assert.equal((await authorityRequest(request(),f.services,f.now)).status,200);assert.equal(await f.services.storage.get('pending-repository:7'),undefined);assert.equal((await f.services.storage.get(`authority:${id}`)).state,'completed');await assert.rejects(authorize(f.bundle,f.services,f.now));await assert.rejects(authorize(await f.bundleFor(f.intent,{runID:61}),f.services,f.now));await authorize(await f.bundleFor({...f.intent,nonce:'2'.repeat(64)}),f.services,f.now);});
test('unknown fields and missing private verifier bindings deny without exposing approval bytes',async()=>{const f=await fixture();const response=await authorityRequest(new Request('https://internal/v1/authorization/admit',{method:'POST',body:JSON.stringify({...f.bundle,hardwareVerified:true})}),f.services,f.now);assert.equal(response.status,403);assert.equal((await response.text()).includes(f.bundle.owner.signature),false);const coordinator=new AuthorizationCoordinator({storage:storage()},{AUTHORIZATION_ENABLED:'true'});assert.equal((await coordinator.fetch(new Request('https://internal/v1/authorization/load',{method:'POST',body:'{}'}))).status,503);});

test('policy rotation invalidates a retained exact run before credential issuance',async()=>{
 const f=await fixture();await authorize(f.bundle,f.services,f.now);const saved=await f.services.storage.get(`authority:${id}`);
 f.services.policy.current=async()=>({...f.policy,revision:2,digest:'3'.repeat(64),executorTrust:{...f.trust,acceptedPolicyRevision:2,acceptedPolicyDigest:'3'.repeat(64)}});
 const response=await authorityRequest(new Request('https://internal/v1/authorization/check',{method:'POST',body:JSON.stringify({operationID:id,...saved.record})}),f.services,f.now);assert.equal(response.status,403);
});

test('private completion readback preserves admitted payload after expiry without reopening authority',async()=>{
 const f=await fixture();await authorize(f.bundle,f.services,f.now);
 f.services.policy.current=async()=>{throw Error('No new authorization permitted');};f.services.hardware.verify=async()=>{throw Error('No new authorization permitted');};
 const req=body=>new Request('https://internal/v1/authorization/completion-record',{method:'POST',body:JSON.stringify(body)});
 const response=await authorityRequest(req({operationID:id}),f.services,f.now+1000);assert.equal(response.status,200);const view=await response.json();assert.equal(view.ledgerPayload.commitSHA,f.intent.commitSHA);assert.equal(view.record.operation.id,id);assert.equal(view.recordDigest,await digest(view.record));
 assert.equal((await authorityRequest(req({operationID:id,verified:true}),f.services)).status,403);
 const saved=await f.services.storage.get(`authority:${id}`);saved.bundle.owner.signature='altered';await f.services.storage.put(`authority:${id}`,saved);
 assert.equal((await authorityRequest(req({operationID:id}),f.services)).status,403);
});
