import {test} from 'node:test';import assert from 'node:assert/strict';
import {enrollmentJournal} from '../src/enrollment/journal.mjs';
const id='d'.repeat(64),session={ownerID:34,role:'writer',expiresAt:2000,manifestDigest:'e'.repeat(64)};
function fixture(){
 let queue=Promise.resolve();const records=new Map();let retained,exchanges=0,failVerify=false,loseTransition=false;
 const storage={get:async k=>structuredClone(records.get(k)),transaction:fn=>{const result=queue.then(()=>fn({get:async k=>structuredClone(records.get(k)),put:async(k,v)=>{if(loseTransition&&v.state==='staged'){loseTransition=false;throw Error('outage');}records.set(k,structuredClone(v));}}));queue=result.catch(()=>{});return result;}};
 const vault={stage:async(ref,c)=>{retained={reference:ref,...c,state:'staged'};},status:async()=>retained,activate:async(ref,verify)=>{await verify({appID:retained.appID,ownerID:retained.ownerID,role:retained.role});retained.state='active';}};
 const provider={exchangeManifestCode:async()=>{exchanges++;return {id:12,pem:'secret-pem',webhook_secret:'secret-hook',client_secret:'secret-client'};},verifyApp:async()=>{if(failVerify)throw Error('not verified');}};
 return {records,vault,provider,j:enrollmentJournal(storage,vault,provider,()=>1000),count:()=>exchanges,fail:()=>{failVerify=true;},recover:()=>{failVerify=false;},lose:()=>{loseTransition=true;}};
}
test('enrollment reserves conversion once and persists no code or provider secrets',async()=>{const f=fixture();await f.j.create(id,session);const result=await f.j.exchange(id,'callback-code');assert.equal(result.state,'active');assert.equal(f.count(),1);await assert.rejects(f.j.exchange(id,'callback-code'));assert.deepEqual(await f.j.reconcile(id),result);for(const x of ['callback-code','secret-pem','secret-hook','secret-client'])assert.equal(JSON.stringify([...f.records]).includes(x),false);});
test('staged credentials survive verification failure and reconcile without conversion',async()=>{const f=fixture();await f.j.create(id,session);f.fail();await assert.rejects(f.j.exchange(id,'code'));assert.equal((await f.j.status(id)).state,'staged');f.recover();assert.equal((await f.j.reconcile(id)).state,'active');assert.equal(f.count(),1);});
test('vault persistence before journal outage recovers; lost provider response never retries',async()=>{const f=fixture();await f.j.create(id,session);f.lose();await assert.rejects(f.j.exchange(id,'code'));assert.equal((await f.j.reconcile(id)).state,'active');assert.equal(f.count(),1);const g=fixture();g.provider.exchangeManifestCode=async()=>{throw Error('lost response');};await g.j.create(id,session);await assert.rejects(g.j.exchange(id,'code'));await assert.rejects(g.j.exchange(id,'code'));await assert.rejects(g.j.reconcile(id));assert.equal((await g.j.status(id)).state,'exchanging');});
test('concurrent callback reserves one exchange and invalid or expired sessions reject',async()=>{const f=fixture();await f.j.create(id,session);const results=await Promise.allSettled([f.j.exchange(id,'code'),f.j.exchange(id,'code')]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.count(),1);await assert.rejects(f.j.create('f'.repeat(64),{...session,expiresAt:999}));await assert.rejects(f.j.create('f'.repeat(64),{...session,verified:true}));});
