import {test} from 'node:test';
import assert from 'node:assert/strict';
import {execute} from '../../delivery_control/src/execute.mjs';
import {executionRequest} from '../src/execution/http.mjs';
const s=c=>c.repeat(40),id='a'.repeat(64);
function fixture(change={}){let writes=0,revokes=0,reports=[],tip=s('b');const grant={operationID:id,token:'SECRET-TEST-TOKEN',operationExpiresAt:2000,intent:{repository:'owner/project',repositoryID:7,branch:'main',baseSHA:s('b'),commitSHA:s('c'),treeSHA:s('d')},...change};const fetcher=async(url,options={})=>{url=String(url);if(url.includes('.actions.githubusercontent.com'))return Response.json({value:'fake-oidc'});if(url.endsWith('/lease'))return Response.json(grant);if(url.endsWith('/complete')){reports.push(JSON.parse(options.body).outcome);return Response.json({state:'reconciled'});}if(url.endsWith('/installation/token')){revokes++;return new Response(null,{status:204});}if(url.endsWith('/repos/owner/project'))return Response.json({id:7});if(url.includes('/git/commits/'))return Response.json({sha:s('c'),parents:[{sha:s('b')}],tree:{sha:s('d')},verification:{verified:true}});if(options.method==='PATCH'){writes++;assert.deepEqual(JSON.parse(options.body),{sha:s('c'),force:false});tip=s('c');return Response.json({});}return Response.json({object:{sha:tip}});};return {fetcher,options:{operationID:id,controller:'https://controller.example/',oidcURL:'https://run.actions.githubusercontent.com/token',oidcBearer:'request-token',audiencePrefix:'repoctl'},writes:()=>writes,revokes:()=>revokes,reports};}
test('central executor updates exact candidate, revokes credential and reports',async()=>{const f=fixture();assert.equal((await execute(f.options,f.fetcher,()=>1000)).outcome,'updated');assert.equal(f.writes(),1);assert.equal(f.revokes(),1);assert.deepEqual(f.reports,['updated']);});
test('expired grants cannot write and still revoke',async()=>{const f=fixture({operationExpiresAt:500});await assert.rejects(execute(f.options,f.fetcher,()=>1000));assert.equal(f.writes(),0);assert.equal(f.revokes(),1);});
test('malicious OIDC URL and shell-shaped operation IDs reject before networking',async()=>{const f=fixture();await assert.rejects(execute({...f.options,operationID:'$(bad)'},()=>{throw Error('network called');}));await assert.rejects(execute({...f.options,oidcURL:'https://evil.example/token'},()=>{throw Error('network called');}));});
test('lost update response reports uncertain outcome without another write',async()=>{const f=fixture();const fetcher=async(url,options)=>{const result=await f.fetcher(url,options);if(options?.method==='PATCH')throw Error('lost response');return result;};await assert.rejects(execute(f.options,fetcher,()=>1000));assert.equal(f.writes(),1);assert.equal(f.revokes(),1);assert.deepEqual(f.reports,['uncertain']);});
test('HTTP execution boundary rejects unknown fields with no-store and sanitized response',async()=>{const r=await executionRequest(new Request('https://controller.example/v1/execution/lease',{method:'POST',body:JSON.stringify({operationID:id,oidcToken:'PRIVATE-JWT',command:'evil'})}),{},{});assert.equal(r.status,403);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal((await r.text()).includes('PRIVATE-JWT'),false);});
import {reconcileExecution} from '../src/execution/reconcile.mjs';
test('completion without an issued lease rejects before any ref observation',async()=>{let reads=0;await assert.rejects(reconcileExecution({operationID:id,oidcToken:'fake',outcome:'updated'},{operations:{read:async()=>({}),readLease:async()=>undefined},observe:{tip:async()=>{reads++;}}},{}));assert.equal(reads,0);});
test('executor connects through real HTTP broker OIDC verification and independent completion',async()=>{
 const now=Math.floor(Date.now()/1000),f=fixture({operationExpiresAt:now+200});
 const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
 const key=await crypto.subtle.exportKey('jwk',pair.publicKey);key.kid='integration';
 const trust={audiencePrefix:'repoctl',repository:'owner/delivery_control',repositoryID:10,ownerID:20,ref:'refs/heads/main',workflowRef:'owner/delivery_control/.github/workflows/promote.yml@refs/heads/main',workflowSHA:s('a'),jobWorkflowRef:'owner/delivery_control/.github/workflows/executor.yml@refs/heads/main',jobWorkflowSHA:s('a'),actorIDs:[30],eventNames:['workflow_dispatch'],installationID:50,repositoryIDs:[7],acceptedPolicyRevision:1,acceptedPolicyDigest:'b'.repeat(64),targetRef:'refs/heads/main'};
 let count=0,lease,completed=false;
 async function token(){const c={iss:'https://token.actions.githubusercontent.com',aud:`repoctl:${id}`,iat:now,nbf:now,exp:now+300,repository:trust.repository,repository_id:'10',repository_owner_id:'20',ref:trust.ref,workflow_ref:trust.workflowRef,workflow_sha:trust.workflowSHA,job_workflow_ref:trust.jobWorkflowRef,job_workflow_sha:trust.jobWorkflowSHA,actor_id:'30',event_name:'workflow_dispatch',runner_environment:'github-hosted',run_id:'60',run_attempt:'1',jti:`unique-integration-${++count}`};const enc=v=>Buffer.from(JSON.stringify(v)).toString('base64url');const b=enc({alg:'RS256',kid:key.kid})+'.'+enc(c);return b+'.'+Buffer.from(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,Buffer.from(b))).toString('base64url');}
 const op={id,state:'authorized',operation:'promote',expiresAt:now+200,authorizationProvider:'hardware',hardwareEnrollmentVerified:true,policyRevision:1,policyDigest:trust.acceptedPolicyDigest,targetRef:trust.targetRef,repositoryID:7,runID:60,runAttempt:1};
 const intent={repository:'owner/project',repositoryID:7,branch:'main',baseSHA:s('b'),commitSHA:s('c'),treeSHA:s('d')};
 const services={serialize:async(_,fn)=>fn(),operations:{read:async()=>op,readLease:async()=>lease,usedJTI:async()=>false,reserve:async v=>lease=v,issued:async v=>lease=v,markUncertain:async()=>{},completed:async()=>completed=true,uncertain:async()=>{},degraded:async()=>{}},jwks:async()=>({keys:[key]}),verifyAuthorization:async()=>{},executionIntent:async()=>intent,credentials:{issueInstallationToken:async()=>({token:'SECRET-TEST-TOKEN',expiresAt:now+3600,repositoryIDs:[7],permissions:{contents:'write'}}),revoke:async()=>{}},observe:{tip:async()=>{const r=await f.fetcher('https://api.github.com/repos/owner/project/git/ref/heads/main');return (await r.json()).object.sha;}},verifyCompletion:async()=>{},receipts:{finalize:async()=>({digest:'d'.repeat(64)})}};
 services.complete=(input,t)=>reconcileExecution(input,services,t);
 const transport=async(url,options)=>{if(String(url).includes('.actions.githubusercontent.com'))return Response.json({value:await token()});if(String(url).startsWith('https://controller.example'))return executionRequest(new Request(url,options),services,trust);return f.fetcher(url,options);};
 await execute(f.options,transport,()=>now);assert.equal(f.writes(),1);assert.equal(f.revokes(),1);assert.equal(completed,true);
});
