import {test} from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {mkdtemp,realpath,writeFile,chmod,rm,access} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {recoveryRuntime} from '../src/archive/recovery-runtime.mjs';import {recoverySigner} from '../src/archive/recovery-job.mjs';import {recoveryPublication} from '../src/archive/publication.mjs';
test('composed recovery restores packed Git, verifies objects, signs, publishes and cleans on success or denial',async()=>{
 const root=await realpath(await mkdtemp(join(tmpdir(),'recovery-runtime-')));try{
 const env={PATH:'/usr/bin:/bin',HOME:root,GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1',GIT_AUTHOR_NAME:'test',GIT_AUTHOR_EMAIL:'test@example.com',GIT_COMMITTER_NAME:'test',GIT_COMMITTER_EMAIL:'test@example.com'},git=(...args)=>execFileSync('/usr/bin/git',args,{cwd:root,env}).toString().trim();
 git('init','-q');await writeFile(join(root,'file'),'base');git('add','.');git('commit','-qm','base');const sourceSHA=git('rev-parse','HEAD');await writeFile(join(root,'file'),'new');git('add','.');git('commit','-qm','child');const commitSHA=git('rev-parse','HEAD'),treeSHA=git('rev-parse','HEAD^{tree}');git('gc','--prune=now');
 const binary=join(root,'fk'),trace=join(root,'trace');await writeFile(binary,`#!${process.execPath}\nconst fs=require('node:fs');let b='';process.stdin.on('data',x=>b+=x);process.stdin.on('end',()=>{const r=JSON.parse(b),p=r.parameters;fs.appendFileSync(process.env.TRACE,p.destination+'\\n');fs.mkdirSync(p.destination);let output;if(r.operation==='snapshot.restore')output={manifestDigest:p.expectedManifestDigest,verification:'full-ciphertext-and-authenticated-plaintext'};else{fs.cpSync(process.env.SOURCE,p.destination+'/.git',{recursive:true});output={gitFsck:true,allLocalObjectsRestored:true,unsafeConfigAndHooksActivated:false};}console.log(JSON.stringify({schemaVersion:1,requestID:r.requestID,operation:r.operation,status:'succeeded',output}));});`);await chmod(binary,0o700);
 const archiveDigest='a'.repeat(64),policyDigest='b'.repeat(64),intent={repositoryID:7,commitSHA,sourceSHA,treeSHA,archiveDigests:[archiveDigest]},pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},false,['sign','verify']),signer=recoverySigner({keyID:'recovery',privateKey:pair.privateKey,publicKey:pair.publicKey});let stored,puts=0,deny=false;
 const publication=recoveryPublication({clock:()=>1000,configurations:[{repositoryID:7,policyDigest,trustedKeys:signer.trustedKeys}],bucket:{get:async()=>stored?{size:stored.length,arrayBuffer:async()=>stored.buffer.slice(stored.byteOffset,stored.byteOffset+stored.byteLength)}:null,put:async(k,b)=>{puts++;stored=Buffer.from(b);}}});
 const runtime=recoveryRuntime({clock:()=>1000,policyDigest,gitExecutable:'/usr/bin/git',signer,flarekit:{executable:binary,configuration:join(root,'config'),environment:{SOURCE:join(root,'.git'),TRACE:trace},archives:[{repositoryID:7,archiveDigest,gitManifestDigest:'c'.repeat(64),vault:root,snapshotID:'snapshot',identity:{provider:'keychain',reference:'recovery'}}]},transport:{origin:'https://upload.example/',audiencePrefix:'recovery',oidcURL:'https://run.actions.githubusercontent.com/token',oidcBearer:'REQUEST',runID:60,runAttempt:1,fetcher:async(url,o)=>{if(new URL(url).hostname.endsWith('.actions.githubusercontent.com'))return Response.json({value:'OIDC'});if(deny)return new Response('',{status:403});return Response.json(await publication.publish(JSON.parse(o.body).publication));}}});
 assert.equal((await runtime.run(intent)).published,true);assert.equal(puts,1);deny=true;await assert.rejects(runtime.run(intent));
 const {readFile}=await import('node:fs/promises');for(const path of (await readFile(trace,'utf8')).trim().split('\n'))await assert.rejects(access(path));
 }finally{await rm(root,{recursive:true,force:true});}
});
